---
title: "Lab 06 - Functions and iterations"
author: "Louis Newton (s2474470)"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )
```


## Exercise 1

```{r}
diamonds_clean <- diamonds %>% filter(length_mm != 0 & width_mm != 0 & depth_mm != 0)
diamonds_dirty <- diamonds %>% filter(length_mm == 0 | width_mm == 0 | depth_mm == 0)
diamonds_clean %>% count(cut)
diamonds_clean %>% count(color)
diamonds_clean %>% count(clarity)
diamonds_clean %>% summarise(mean(carat), median(carat), mean(price))
diamonds_clean %>% select(price, cut) %>% 
  group_by(cut) %>% summarise(mean(price, na.rm  = TRUE))
ggplot(data = diamonds_clean, mapping = aes(x = cut)) +
  geom_bar()

ggplot(data = diamonds_clean, mapping = aes(x = color)) +
  geom_bar()
```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

# Overall table_mm arithmetic mean?
diamonds %>% summarise(mean(table_mm, na.rm = TRUE))





# table_mm arithmetic mean within each clarity category
diamonds %>% group_by(clarity) %>% summarise(mean(table_mm, na.rm = TRUE))

diamonds %>% summarise(
  across(where(is.numeric), \(x) mean(x))) %>% 
  rename("avg_price" = price,
         "avg_length" = length_mm,
         "avg_width" = width_mm,
         "avg_depth" = depth_mm 
         )
```
Mean table length decreases as level of clarity increases.

```{r}
# calculate the arithmetic mean across all numeric variables




```

## Exercise 3

```{r}
# Write gmean() command



```

## Exercise 4

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples


```


## Exercise 5

```{r}
# Copy gmean() from Ex 3 and edit it to check the input





# Copy your code from Ex 4 to test your new command





```

## Exercise 6

```{r}
# replicate the for loop from Ex 4 using the map (or a similar) function

```


## Exercise 7

```{r}
# Overall table_mm arithmetic mean, median, and geometric mean?






# Arithmetic mean, median, and geometric mean of table_mm within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```

## Exercise 10 (optional)

_Do derivation on paper, unless you know how to write LaTeX code_
